import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideNav from './components/SideNav';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ margin: 0, padding: 0, display: 'flex' }}>
        <SideNav />
        <main style={{ flex: 1, padding: '24px', backgroundColor: '#f9fafb' }}>
          {children}
        </main>
      </body>
    </html>
  );
}
